### PR TITLE
Update GridcoinAutoNode.sh

### PR DESCRIPTION
**Pull request by Peppernrino**
now compiles from source instead of ppa.
uses snapshot instead of bootstrap, need to include a warning on read.me that bootstrap requires 1GB+ of RAM.
fixed google DNS.
changed order of some things.
added new nodes.
changed autostart.
put nodes at the start.... apparently, they're supposed to be.
added install instructions.
remove ipv6 disable.

### CODE REVIEW

**Comment by NeuralMiner** [comment]
Personally I think any node address that does any kind of dynamic choosing of nodes in the background should begin remmed out with a note explaining what they are. Some users might want to know exactly what nodes they're connecting to and/or choose specific nodes. It's not made clear that some of the addresses are just forwarders to other nodes.

**Comment by Peppernrino** [comment]
are you referring to the gridcoin.is.dopeshit.net node that does the "round-robin" connection thing?

**Comment by NeuralMiner** [comment]
Correct.

**Comment by Peppernrino** [comment]
updated.

**Comment by grctest** [comment]
I'd prefer to have the option of either compiling from source or using the ppa's, because $5 VPS are unable to compile without swap space first configured.

**Comment by Peppernrino** [comment]
i see the merit in this request. i'll get rid of the compile part for now, but it should be kept in mind that $5 VPS's aren't going to be able to support the network in the near future. 1GB of RAM barely covers it. i recently upgraded my nodes from 2 x 512mb openvz to 1 x 2gb kvm, and it costs about $7 a month, which is the same cost as one of the other nodes. one was $5, one was $7.

**Pull request closed without merging**
